Add Single Request subscription mode
nats-io/nats.net.v1 pull request #167
Opened 2017-06-21 18:31 UTC by sixlettervariables

This implements #158 by default, and provides `Options.UseOldRequestStyle` to change the behavior. The implementation mirrors go-nats, with differences expected for the differences in framework/language.

- Adds an InFlightRequest object to track each request, as well as provide a common cancellation token source.
- Uses a GUID for the inbox (per #161)
- Does not change the public API for requests, instead choosing to branch based on the chosen request model
- Unit tests expanded to test both old and new strategies

2017-06-23 22:33 UTC, ColinSullivan1 requested changes
@sixlettervariables , Overall, it looks great, thanks!  Just one change requested.

2017-06-23 22:33 UTC, ColinSullivan1 commented on NATS.Client/Conn.cs
> +            public CancellationToken Token { get; }
Could you add `set;` to `CancellationToken` and  `TaskCompletionSource`? To date, we've been maintaining C# 5 compatibility (will move to C# 6 fairly soon, though).

2017-06-24 14:23 UTC, sixlettervariables commented on NATS.Client/Conn.cs
> +                    removeTimedoutRequest(request.Id);
Missed a throw.

2017-06-26 19:36 UTC, ColinSullivan1 commented
LGTM!

2017-06-26 19:37 UTC, merged