Adds offset+count overloads to Publish and Request
nats-io/nats.net.v1 pull request #182
Opened 2017-09-22 13:26 UTC by sixlettervariables

Implements #171.

2017-09-25 18:41 UTC, ColinSullivan1 commented
@sixlettervariables Thanks! (as always).  I'll starting reviewing this today.

2017-09-26 15:42 UTC, ColinSullivan1 commented on NATS.Client/Conn.cs
> +            publish(msg.Subject, msg.Reply, msg.Data, 0, count);
Could use the expression above and avoid declaring count.  This is where I wish C# had macros.

2017-09-26 16:19 UTC, ColinSullivan1 requested changes
Thanks for the contribution!  Overall LGTM.  Just one concern about duplicate arg checking.

2017-09-26 16:19 UTC, ColinSullivan1 commented on NATS.Client/Conn.cs
> +            else if (offset < 0)
Maybe a comment instead of these arg checks?  `offset`, `count`, and the overrun will be checked by the `publish` method later on.   It'll also keep the arg checking logic in one place.

2017-09-26 16:19 UTC, ColinSullivan1 commented on NATS.Client/Conn.cs
> +            else if (offset < 0)
Same as above regarding argument checking.

2017-09-26 16:19 UTC, ColinSullivan1 commented on NATS.Client/Conn.cs
> +
Total nitpick, but there's an extra line here.

2017-09-26 16:19 UTC, ColinSullivan1 commented on NATS.Client/SyncSub.cs
> +                if (d == localMax)
Thanks, good catch!

2017-09-26 16:19 UTC, ColinSullivan1 commented on NATS.Client/Conn.cs
> +        private Msg oldRequest(string subject, byte[] data, int offset, int count, int timeout)
This will eventually be deprecated, but thanks for adding the offset/count to these APIs.

2017-09-26 19:23 UTC, sixlettervariables commented on NATS.Client/Conn.cs
> +            else if (offset < 0)
Done.

2017-09-26 19:23 UTC, sixlettervariables commented on NATS.Client/Conn.cs
> +            else if (offset < 0)
Done.

2017-09-26 19:24 UTC, sixlettervariables commented on NATS.Client/Conn.cs
> +
Honestly don't know how I missed that. I nitpick the mess out of whitespacing!

2017-09-27 02:37 UTC, ColinSullivan1 approved these changes
LGTM - thanks!

2017-09-27 02:38 UTC, merged