remove unnecessary lock during processMsg
nats-io/nats.net.v1 pull request #188
Opened 2017-11-06 10:12 UTC by tamnm

Lock during conn.processMsg is unnecessary. It's single thread processing, already thread safe.

2017-11-06 20:39 UTC, ColinSullivan1 commented on NATS.Client/Conn.cs
> +                s = subs[msgArgs.sid];
`subs` can be accessed through unsubscribe outside of the readLoop.

2017-11-06 20:45 UTC, ColinSullivan1 commented on NATS.Client/Subscription.cs
>          internal bool tallyMessage(long bytes)
Good catch - this looks to be an unnecessary lock.  Would you mind adding a comment above the method (line 109): `// Caller must lock`.

2017-11-06 20:50 UTC, ColinSullivan1 requested changes
Thanks for the contribution!  

The conn lock is needed to properly handle unsubscribe called from application code. 

Good catch with the subscription lock.  That can be removed.

Could you resubmit the PR using only the changes to Subscription.cs?

2017-11-06 20:54 UTC, ColinSullivan1 commented on NATS.Client/Conn.cs
> +                s = subs[msgArgs.sid];
Th connection lock also protects statistics being gathered.

2017-11-07 06:42 UTC, tamnm commented
@ColinSullivan1 I reverted changes in conn.cs, added comment into Subscription

2017-11-07 19:30 UTC, ColinSullivan1 approved these changes
LGTM - thanks for the contribution!  After tests pass, I'll merge.

2017-11-09 22:19 UTC, ColinSullivan1 commented
AppVeyor is having issues that seem related to resource constraints.  I tested manually and all tests pass.  Thanks again for the contribution.

2017-11-09 22:20 UTC, merged