Couple of small fixes
nats-io/nats.net.v1 pull request #245
Opened 2019-02-16 09:53 UTC by lanfeust69

See messages of individual commits

2019-02-26 14:09 UTC, sixlettervariables requested changes
Couple of changes.

2019-02-26 14:09 UTC, sixlettervariables commented on NATS.Client/Conn.cs
> +                    task.ContinueWith(t => t.Exception);
```suggestion
                    task.ContinueWith(t => GC.KeepAlive(t.Exception), TaskContinuationOptions.OnlyOnFaulted);
```

2019-02-26 14:09 UTC, sixlettervariables commented on NATS.Client/EncodedConn.cs
> +            if (onSerialize == null)
Should protect against `onSerialize` changing between the null check and the call:
```csharp
    Serializer serializer = onSerialize;
    if (serializer == null)
        throw new NATSException("IEncodedConnection.OnSerialize must be set (.NET core only).");

    byte[] data = serializer(o);
```

2019-02-26 18:35 UTC, lanfeust69 commented on NATS.Client/Conn.cs
> +                    task.ContinueWith(t => t.Exception);
I don't understand the purpose of `GC.KeepAlive` here.

Regarding limiting the continuation to Faulted tasks, it probably makes sense, but should be done separately (along with the `GC.KeepAlive` if deemed useful) to address the other places where this pattern has been introduced in dde17f208afeb9133bf45b23fa4683b26cd7ad49 and 81f08b0d2d34dfc4af66fa7dffbfeaac442f8820.

2019-02-26 18:35 UTC, lanfeust69 commented on NATS.Client/EncodedConn.cs
> +            if (onSerialize == null)
Is it really a good idea ?

In practice, `OnSerialize` will be set once and never touched, and we only want a better error than the dreaded `NullReferenceException` if not set.

OTOH, if by extraordinary it is a voluntary change, maybe using the "old" one after the change could be a real problem (for instance there could be some kind of disposable buffer involved, which has been disposed). Seems worse than changing the type of the exception, I think. And of course, adding a proper lock mechanism is surely too expensive for such an unlikely scenario.

2019-02-26 19:03 UTC, watfordgnf commented on NATS.Client/Conn.cs
> +                    task.ContinueWith(t => t.Exception);
It ensures the unused exception is truly observed, and not thrown away. Good catch on the other areas which could use that.

2019-02-26 19:13 UTC, lanfeust69 commented on NATS.Client/Conn.cs
> +                    task.ContinueWith(t => t.Exception);
Sorry, still don't get it...

According to the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.gc.keepalive), `GC.KeepAlive` :

> References the specified object, which makes it ineligible for garbage collection from the start of the current routine to the point where this method is called.

But it is already referenced, as it is about to be set as the `Result` of the `Task<Exception>` created by `ContinueWith()`, isn't it ?

2019-02-27 14:10 UTC, watfordgnf commented on NATS.Client/Conn.cs
> +                    task.ContinueWith(t => t.Exception);
This is a pattern seen in https://github.com/StackExchange/StackExchange.Redis/blob/master/src/StackExchange.Redis/TaskExtensions.cs

I've reached out to @mgravell for more details.

2019-02-27 18:21 UTC, lanfeust69 commented on NATS.Client/Conn.cs
> +                    task.ContinueWith(t => t.Exception);
I get it now : the `GC.KeepAlive()` isn't useful for "observing" the Exception (that was already OK), but to change the `ContinueWith()` overload that will be used : it is now the one that takes an `Action<Task>`, and **returns a simple `Task`** (instead of a `Task<Exception>` for the current overload that accepts a `Func<Task, Exception>`). As this task will always complete synchronously, it might be optimized to return the singleton `Task.CompletedTask` (when available), avoiding an allocation.

So this is actually a small optimization, especially when associated with the `OnlyOnFaulted` which should mean few actual continuations. Moreover, this is in the connection step, so probably few calls, it would be more interesting in the other place where this pattern is used (`Connection.setupRequest`).

2019-03-19 13:18 UTC, watfordgnf approved these changes

2019-03-19 16:37 UTC, ColinSullivan1 approved these changes
LGTM.  Thanks for the contribution!

2019-03-19 17:25 UTC, merged