Add Reconnect Buffering
nats-io/nats.net.v1 pull request #284
Opened 2019-08-30 23:14 UTC by ColinSullivan1

Implement reconnect buffer sizing and disabling, a feature available in the golang client.

Resolves #251.

Signed-off-by: Colin Sullivan <colin@synadia.com>

2019-09-03 15:16 UTC, watfordgnf requested changes

2019-09-03 15:16 UTC, watfordgnf commented on NATS.Client/Conn.cs
> +                        if (opts.ReconnectBufferSize == -1)
```suggestion
                        if (rbsize == -1)
```

2019-09-03 15:16 UTC, watfordgnf commented on NATS.Client/Options.cs
> +                    throw new ArgumentOutOfRangeException("value", "Subscription batch size must be greater than -1");
Message is incorrect.

2019-11-04 19:01 UTC, ColinSullivan1 commented
Most of the PR was copied and used in #314.

2019-11-04 19:01 UTC, closed without merging