Adds Observable support
nats-io/nats.net.v1 pull request #304
Opened 2019-10-15 11:08 UTC by danielwertheim

This PR adds observable support as defined in #303

2019-10-15 14:08 UTC, watfordgnf reviewed
Some general comments, liking the way this looks!

2019-10-15 14:08 UTC, watfordgnf commented on src/NATS.Client/Rx/INATSObservable.cs
> +    /// Marker interface to have shipped extension methods to not interfear
```suggestion
    /// Marker interface to have shipped extension methods to not interfere
```

2019-10-15 14:08 UTC, watfordgnf commented on src/NATS.Client/Rx/INATSObservable.cs
> +    /// with offical RX extensions.
```suggestion
    /// with official RX extensions.
```

2019-10-15 14:08 UTC, watfordgnf commented on src/NATS.Client/Rx/NATSObservable.cs
> +            if(!subscriptions.TryAdd(sub.Id, sub))
Should we consider returning the existing subscription if this is called twice?

2019-10-15 14:08 UTC, watfordgnf commented on src/NATS.Client/Rx/Ops/DelegatingObserver.cs
> +            this.onNext = onNext;
```suggestion
            this.onNext = onNext ?? throw new ArgumentNullException(nameof(onNext));
```

2019-10-15 14:08 UTC, watfordgnf commented on src/NATS.Client/Rx/Ops/SafeObserver.cs
> +            this.onNext = onNext;
```suggestion
            this.onNext = onNext ?? throw new ArgumentNullException(nameof(onNext));
```

2019-10-15 14:08 UTC, watfordgnf commented on src/NATS.Client/Rx/NATSObservable.cs
> +                Id = observer.GetHashCode();
We're using hash codes for uniqueness, however, someone could conceptually make their own and our invariant would be broken. We're looking for unique-by-reference-equality, right?

2019-10-15 14:08 UTC, watfordgnf commented on src/NATS.Client/Rx/Ops/MapObservable.cs
> +            => src.SubscribeSafe(new MapObserver(observer, mapper));
Does this need a test for `observer` against `null`?

2019-10-15 14:08 UTC, watfordgnf commented on src/NATS.Client/Rx/Ops/WhereObservable.cs
> +            => src.SubscribeSafe(new WhereObserver(observer, predicate));
Does this need a test for `observer` against `null`?

2019-10-15 14:08 UTC, watfordgnf commented on src/NATS.Client/Rx/RxExtensions.cs
> +            => cn.SubscribeAsync(subject).ToObservable();
We should probably test `cn` against `null`.

2019-10-15 14:36 UTC, danielwertheim commented on src/NATS.Client/Rx/NATSObservable.cs
> +                Id = observer.GetHashCode();
Just as if we would add the observer to e.g. a HashSet. We could switch for a GUID if you feel it is that important?

2019-10-15 14:37 UTC, danielwertheim commented on src/NATS.Client/Rx/NATSObservable.cs
> +            if(!subscriptions.TryAdd(sub.Id, sub))
But why should you call it twice?

2019-10-15 14:46 UTC, danielwertheim commented on src/NATS.Client/Rx/Ops/DelegatingObserver.cs
> +            this.onNext = onNext;
Completely missed I could accept suggestion. It's been fixed though

2019-10-15 14:46 UTC, danielwertheim commented on src/NATS.Client/Rx/Ops/SafeObserver.cs
> +            this.onNext = onNext;
Fixed

2019-10-15 14:47 UTC, watfordgnf commented on src/NATS.Client/Rx/NATSObservable.cs
> +            if(!subscriptions.TryAdd(sub.Id, sub))
Perhaps this is a non-issue if users would never logically pass the same observer twice to Subscribe.

2019-10-15 14:48 UTC, danielwertheim commented on src/NATS.Client/Rx/Ops/MapObservable.cs
> +            => src.SubscribeSafe(new MapObserver(observer, mapper));
The `MapObserver` now requires it.

2019-10-15 14:49 UTC, danielwertheim commented on src/NATS.Client/Rx/Ops/WhereObservable.cs
> +            => src.SubscribeSafe(new WhereObserver(observer, predicate));
The WhereObserver now requires it.

2019-10-15 15:01 UTC, danielwertheim commented on src/NATS.Client/Rx/RxExtensions.cs
> +            => cn.SubscribeAsync(subject).ToObservable();
Fixed

2019-10-15 15:07 UTC, danielwertheim commented on src/NATS.Client/Rx/NATSObservable.cs
> +                Id = observer.GetHashCode();
The idea though, is that you should not add the exact same observer twice, hence e.g. a GUID would not work as I see it.

2019-10-15 15:40 UTC, danielwertheim commented
This would also solve #149

2019-10-15 15:54 UTC, watfordgnf commented on src/NATS.Client/Rx/NATSObservable.cs
> +                Id = observer.GetHashCode();
What would be the downside to making the key simply the observer itself? We'd retain HashSet semantics and avoid the odd situation where two equal hash codes could occur for two distinct objects.

2019-10-15 18:45 UTC, danielwertheim commented on src/NATS.Client/Rx/NATSObservable.cs
> +                Id = observer.GetHashCode();
I guess it's just habit of as much as possible using a value object as a key due to allocations etc.

Using the "object" as the key will call it's GetHashCode when adding and GetHashCode + Equals e.g when getting so I'm not sure how that would solve the issue you want to solve.

2019-10-15 21:17 UTC, ColinSullivan1 requested changes
This looks great!  Some minor comments/typos and a question regarding slow consumers.  Could you add some brief example code into the README?

It doesn't need to be part of this PR (can be separate), but an example project users could reference would go a long way to helping them started with this API.

2019-10-15 21:17 UTC, ColinSullivan1 commented on src/NATS.Client/Rx/INATSObservable.cs
> +﻿// Copyright 2015-2018 The NATS Authors
Minor thing...  Could you update the license headers to be `Copyright 2019 The NATS Authors`?

2019-10-15 21:17 UTC, ColinSullivan1 commented on src/NATS.Client/Rx/NATSObservable.cs
> +                    //Missbehaving observer will remove its subscription
Typo `Misbehaving`.

2019-10-15 21:17 UTC, ColinSullivan1 commented on src/NATS.Client/Rx/NATSObservableSubscription.cs
> +            this.subscription.Start();
I'm wondering if it'd be useful (or feasible) to also setup an AsyncErrorHandler (normally set in [options](https://github.com/nats-io/nats.net/blob/master/src/NATS.Client/Options.cs#L72)) to intercept async errors from the server and invoke `onError` in the observable.  I know these errors are attached to a connection today, but it might be useful to surface slow consumer errors through `onError`.  wdyt?

2019-10-15 21:17 UTC, ColinSullivan1 commented on src/Tests/IntegrationTests/TestRx.cs
> +        public void WhenDispoingAnObserverItShouldNotReceiveMoreMessages()
typo...

2019-10-15 21:17 UTC, ColinSullivan1 commented on src/Tests/IntegrationTests/TestRx.cs
> +        public void WhenDispoingAnObservableNoMoreDispatchesShouldBeDone()
Typo...

2019-10-16 03:51 UTC, danielwertheim commented on src/NATS.Client/Rx/NATSObservableSubscription.cs
> +            this.subscription.Start();
Calling `OnError` would terminate the observer, meaning if the connection comes up again, the subscribed observer would not get any further dispatches. I don't think that is optimal.

2019-10-16 03:58 UTC, danielwertheim commented on src/NATS.Client/Rx/INATSObservable.cs
> +﻿// Copyright 2015-2018 The NATS Authors
Updated the ones added in this PR.

2019-10-16 04:04 UTC, danielwertheim commented on src/Tests/IntegrationTests/TestRx.cs
> +        public void WhenDispoingAnObservableNoMoreDispatchesShouldBeDone()
Fixed

2019-10-16 04:05 UTC, danielwertheim commented on src/Tests/IntegrationTests/TestRx.cs
> +        public void WhenDispoingAnObserverItShouldNotReceiveMoreMessages()
Fixed

2019-10-16 04:06 UTC, danielwertheim commented on src/NATS.Client/Rx/NATSObservable.cs
> +                    //Missbehaving observer will remove its subscription
Fixed

2019-10-16 04:32 UTC, danielwertheim commented
@ColinSullivan1 Added `RxSample` project under Samples and added code to README,

2019-10-16 23:20 UTC, ColinSullivan1 commented on src/NATS.Client/Rx/NATSObservableSubscription.cs
> +            this.subscription.Start();
Ahh, good point.  I agree - thanks.

2019-10-16 23:42 UTC, ColinSullivan1 approved these changes
LGTM.  Thanks - well done!

2019-10-17 00:00 UTC, ColinSullivan1 commented
I think this is ready to be merged.  @watfordgnf , wdyt?

2019-10-17 14:03 UTC, watfordgnf approved these changes

2019-10-18 09:34 UTC, merged