Issue 299 mem leak
nats-io/nats.net.v1 pull request #324
Opened 2019-11-12 16:38 UTC by danielwertheim

A first fix for #299 ensuring a token registration is cleaned up

Without this fix, MB consumption when monitoring in Visual Studio keeps going up. Will look further into that request construct but wanted to provide this fix first.

2019-11-12 16:41 UTC, watfordgnf approved these changes
Ack, I forgot to submit this fix. Looks good!

2019-11-12 22:30 UTC, ColinSullivan1 commented on src/Samples/WinFormsSample/Form1.cs
> +        private async void btnRun_Click(object sender, EventArgs e)
Think it'd be a good idea to disable the button while running, or do you want to allow multiple parallel runs?

2019-11-12 22:30 UTC, ColinSullivan1 commented on src/Samples/WinFormsSample/Form1.cs
> +
Small request - could you initialize one of the list items?  e.g.
`lstScenarios.SelectedItem = lstScenarios.Items[0];`

2019-11-12 22:34 UTC, ColinSullivan1 commented
Other than a few minor things, LGTM.  Forms brings back some old memories.  :)

2019-11-12 22:34 UTC, ColinSullivan1 approved these changes

2019-11-13 03:07 UTC, ColinSullivan1 requested changes
In other testing, it looks like the windows forms project prevents builds on linux and mac.  Could you make that project only build on the windows platform?

2019-11-13 12:26 UTC, danielwertheim commented
@ColinSullivan1 I've now fixed so that all projects can be built in a Linux Docker container and I hope that is good enough verification. Had to exclude explicit support for `.NET4.5` for *non-windows*. Is that OK?

It would be simpler if we stuck to .NET Standard and .NET Core app only but this works for now. To not build the Forms app I had to include a `LinuxRelease` and `LinuxDebug` build config do define that WinForms project should not be built then.

2019-11-13 16:08 UTC, ColinSullivan1 commented
Thanks @danielwertheim.  

>  Had to exclude explicit support for .NET4.5 for non-windows. Is that OK?

Absolutely - the alternative is mono, which imo should be a custom build on a fork at this point.

I would like to keep .NET 4.5 for the time being, there are some users that still require that framework.

> We could look at LinuxDebug and LinuxRelease...

That sounds cleaner to me - might want to add a line in the readme about selecting Linux to building on OSx - we have some users that build .NET there.

2019-11-13 16:11 UTC, ColinSullivan1 approved these changes
LGTM - Thanks!

2019-11-13 16:47 UTC, danielwertheim commented
@ColinSullivan1  I'll add the config solution to this PR and complete it when done.

2019-11-13 16:48 UTC, ColinSullivan1 commented
Thanks!

2019-11-13 18:55 UTC, merged