Async request optimizations
nats-io/nats.net.v1 pull request #339
Opened 2019-11-20 09:39 UTC by danielwertheim

After these changes when running the Benchmarks included I see an increase with about 20% in the request async flow.

When debugging and monitoring GC activity (as discussed in #299), both with and without a specified timeout, I see a highly reduced GC activity also leading to reducing CPU activity.

As it's not possible to specify both `timeout` and `cancellationToken` in the public request API, we could probably remove the need of a `CancellationTokenSource` when a Token has been specified. I'll look into that in another PR.

2019-11-20 11:30 UTC, danielwertheim commented
@ColinSullivan1 having the global subscription created immediately when connected, is that avoided due to not creating an unnecessary subscription? Could this be OK if we added config for the behavior? E.g `options.LazyGlobalSubscriptionInit = true`

2019-11-20 11:39 UTC, danielwertheim commented
Reverted a commit. As it's not possible to specify both `timeout` and `cancellationToken` in the public request API, I thought there was no need for a `CancellationTokenSource` when a Token had been specified but no timeOut had been specified. But it is. Otherwise it never times out and we get a deadlock. Will look into that further and potentially tweak in future PR.

2019-11-20 16:24 UTC, watfordgnf approved these changes
Benchmarks on my machine are certainly faster. Looks good!

2019-11-20 16:24 UTC, watfordgnf commented on src/Samples/WinFormsSample/Form1.cs
> +#if Windows
Should this using be within the `#if` block?

2019-11-20 16:24 UTC, watfordgnf commented on src/Samples/WinFormsSample/Form1.cs
> +                    GC.Collect();
Was this just for debugging?

2019-11-20 16:24 UTC, watfordgnf commented on src/NATS.Client/Conn.cs
> +                        // a NATS timeout exception.
Could it also be a TaskCancelledException?

2019-11-20 16:24 UTC, watfordgnf commented on src/NATS.Client/Conn.cs
> +                requestId = (requestId + long.MaxValue + 1);
Good addition, and likely one that won't impact the `ConcurrentDictionary` as apparently it can only hold `Int32.MaxValue` objects.

2019-11-20 16:28 UTC, watfordgnf commented
In my app's case, we have maybe only one or two request-reply usages. All the rest are publish. We use web services for request/reply (and authorization). In our case, lazily creating the global subscription would be our preference.

Is there a performance gain by creating it immediately for heavy request/reply scenarios?

2019-11-20 21:16 UTC, danielwertheim commented on src/Samples/WinFormsSample/Form1.cs
> +#if Windows
Yes, it should. Auto import gone bad (Alt+Enter). Fixing

2019-11-20 21:18 UTC, danielwertheim commented on src/Samples/WinFormsSample/Form1.cs
> +                    GC.Collect();
Yes and no. Depends on what we want. The form contains many scenarios and wanted to see behavior of GC per scenario without restarting. Could of course be an option. I'll remove and someone else can add it if needed.

2019-11-20 21:19 UTC, danielwertheim commented on src/NATS.Client/Conn.cs
> +                        // a NATS timeout exception.
Do not know. Haven't changed that behavior as far as I know.

2019-11-20 21:26 UTC, danielwertheim commented on src/NATS.Client/Conn.cs
> +                        // a NATS timeout exception.
Just tried it by cancelling a running request and the `OperationCanceledException` is not thrown on the sync path where this is. Added explicit handler for that ex to test.

2019-11-20 21:28 UTC, danielwertheim commented on src/NATS.Client/Conn.cs
> +                requestId = (requestId + long.MaxValue + 1);
I'm not following. I'm guessing the dictionary held strings due to the fact that it's parsed out on the incoming reply from the subject and there you don't want to pay for converting the string to an int/long.

2019-11-20 21:32 UTC, watfordgnf commented on src/NATS.Client/Conn.cs
> +                requestId = (requestId + long.MaxValue + 1);
You're correct , missed we used string rather than longs.

2019-11-21 15:12 UTC, danielwertheim commented
Possibly this will solve #202 as well

2019-11-26 04:12 UTC, ColinSullivan1 commented on src/NATS.Client/Conn.cs
> -        private Dictionary<string, Uri> urls = new Dictionary<string, Uri>();
Thanks - I wonder how much of this stuff I've left in....

2019-11-26 04:29 UTC, ColinSullivan1 commented on src/NATS.Client/Conn.cs
> +                requestId = (requestId + long.MaxValue + 1);
Yes, string was from the original implementation of reply subjects.  If we're using an `int`, I wonder if this would perform even better using ints in the dictionary and converting to a string when publishing.

2019-11-26 04:30 UTC, ColinSullivan1 commented on src/NATS.Client/Conn.cs
> +            if (globalRequestSubscription != null)
It looks like this check should be under the lock below.

2019-11-26 04:35 UTC, ColinSullivan1 requested changes
One question about int vs string for the request id, and there's one check that I think needs to be moved under a lock.  Other than that, LGTM.

2019-11-26 07:41 UTC, danielwertheim commented on src/NATS.Client/Conn.cs
> +                        // a NATS timeout exception.
@watfordgnf resolving. Feel free to re-comment if the "manual test" above is not enough or if I misunderstood anything.

2019-11-26 07:44 UTC, danielwertheim commented on src/NATS.Client/Conn.cs
> +            if (globalRequestSubscription != null)
I might be misunderstanding this, I mean, the lock statement will initialize the subscription once, right? So do we really need the lock statement for the check if it already exists?

2019-11-26 07:56 UTC, danielwertheim commented on src/NATS.Client/Conn.cs
> +                requestId = (requestId + long.MaxValue + 1);
But wouldn't `requestResponseHandler` take a fair amount of perf hit if it first need to extract the string (as of today) then parse the string to an int (new addition if we change to ints) then do the lookup.

I do understand that memory will be reduced though, but is that of any real concern in this case?

2019-11-26 16:21 UTC, ColinSullivan1 commented on src/NATS.Client/Conn.cs
> +            if (globalRequestSubscription != null)
Yeah...  it's possible the value could be cached and different threads would see different values.  Declaring the globalRequestSubscription to be `volatile` *might* work because there is locking below when the variable is used next (ensuring instruction ordering), but risky.  Since there's a locking involved anyhow, probably cleanest just to check under the lock.

This provides some context...
https://stackoverflow.com/questions/154551/volatile-vs-interlocked-vs-lock

2019-11-26 16:24 UTC, ColinSullivan1 commented on src/NATS.Client/Conn.cs
> +                requestId = (requestId + long.MaxValue + 1);
It could, good point.  Memory wouldn't be a big concern, and thinking about it, if there were performance increases here they'd be negligible in terms of the entire request/reply operation.  It's fine as is...

2019-11-26 18:00 UTC, ColinSullivan1 commented on src/NATS.Client/Conn.cs
> +            if (globalRequestSubscription != null)
After discussion on slack and reviewing this again, it's safe.  LGTM.

2019-11-26 18:00 UTC, ColinSullivan1 approved these changes

2019-11-26 18:01 UTC, danielwertheim commented
@ColinSullivan1  For ease, removing interlocked etc. a Guid would be easy. But I guess you don't want a longer subscription etc. than necessary

2019-11-26 19:08 UTC, merged

2019-11-26 19:27 UTC, ColinSullivan1 commented
@danielwertheim , GUID would certainly work, but imo this will be faster and because the first token of the global inbox subject is a random set of bytes seeded by a GUI, we should be safe the way it is, and it'll reduce pressure at scale (smaller subjects as you mentioned).