Add Message Headers
nats-io/nats.net.v1 pull request #394
Opened 2020-07-10 01:34 UTC by ColinSullivan1

Adding NATS message headers to parallel https://github.com/nats-io/nats.go/pull/560.

Also see https://github.com/nats-io/nats-server/blob/master/doc/adr/0004-nats-headers.md

This also includes a change in CI testing to pull the NATS server from a dependency repository.  This allows for testing against unreleased edge features.

2020-07-10 12:53 UTC, watfordgnf reviewed
A few suggestions and comments.

2020-07-10 12:53 UTC, watfordgnf commented on src/NATS.Client/Info.cs
> +                headers = x["headers"].AsBool
```suggestion
                headers = x["headers"].AsBool,
```

2020-07-10 12:53 UTC, watfordgnf commented on src/NATS.Client/Info.cs
> +                ["headers"] = headers
To avoid diffs including this line when another property is added:
```suggestion
                ["headers"] = headers,
```

2020-07-10 12:53 UTC, watfordgnf commented on src/NATS.Client/Msg.cs
> +        internal static readonly int    MinimalValidHeaderLen = Encoding.UTF8.GetBytes(Header + "k:v\r\n\r\n").Length;
Does this mean there is always a value?

2020-07-10 12:53 UTC, watfordgnf commented on src/NATS.Client/Msg.cs
> +            string[] kvpairs = kvs.Split(crlf, StringSplitOptions.RemoveEmptyEntries);
These two splits will start to get expensive on the fast path due to the sheer volume of allocations, likely need to include a TODO to avoid them in favor of getting a UTF8 string directly from the underlying buffer using offsets.

2020-07-10 12:53 UTC, watfordgnf commented on src/NATS.Client/Msg.cs
> +        new public string this[string name]
As this is a public class conceptually someone could use it as a `NameValueCollection` and then the serialization trigger would never execute due to `new`. This would break the behavior:
```csharp
void AddHeaders(NameValueCollection c)
{
    c["Content-Type"] = "application/json";
}
```

2020-07-10 12:53 UTC, watfordgnf commented on src/NATS.Client/Parser.cs
> +        internal int    hdr;
```suggestion
          internal int    hdr;
```

2020-07-10 21:21 UTC, ColinSullivan1 commented on src/NATS.Client/Msg.cs
> +        internal static readonly int    MinimalValidHeaderLen = Encoding.UTF8.GetBytes(Header + "k:v\r\n\r\n").Length;
Good point... while there's some debate it looks like some HTTP header implementations will support empty values - we should as well.  I'll update and test for that.  Thanks.

2020-07-10 22:58 UTC, ColinSullivan1 commented on src/NATS.Client/Msg.cs
> +            string[] kvpairs = kvs.Split(crlf, StringSplitOptions.RemoveEmptyEntries);
Agreed...  Will do.

2020-07-10 23:04 UTC, ColinSullivan1 commented on src/NATS.Client/Msg.cs
> +        new public string this[string name]
Do you think encapsulation would be a better pattern to use here?

2020-07-13 12:49 UTC, watfordgnf commented on src/NATS.Client/Msg.cs
> +        new public string this[string name]
Yeah, given we don't have virtual access to the setter.

2020-07-19 18:27 UTC, ColinSullivan1 commented
I think this should be good to go, would appreciate another quick pass @watfordgnf.

I also addressed the performance issues with Splits.  Had to move up to .NET 4.6 to use the `NameValueCollection` class - while documentation says it's supported in 4.5, the assembly [requires 4.6](https://www.nuget.org/packages/System.Collections.Specialized/4.3.0#dependencies).  

IMO it should be OK to move to 4.6 as the oldest supported framework version.

2020-07-20 12:29 UTC, watfordgnf commented on src/NATS.Client/Msg.cs
> +        new public string this[string name]
I'm not sure sealing this class protects us in this case.

2020-07-20 15:10 UTC, ColinSullivan1 commented on src/NATS.Client/Msg.cs
> +        new public string this[string name]
Any suggestions?

2020-07-20 17:13 UTC, kozlovic requested changes
I don't think you can get away with a simple map. You need to extend to make sure that keys are stored/retried in their canonical form.
Support for multiple values also means that key "Foo" may return an array of ["value1", "value2"] and not a single string of "value1, value2".
Finally, it is possible to receive a multiple line value. So this:
```
NATS/1.0\r\nTwo-Lines: this is\r\n a multilines value\r\n\r\n
```
needs to become "Tow-Lines": "this is a multilines value". Notice that the value spreads on 2 lines and start with a space:" a multilines..." the space will then be removed a concatenated to the previous line.

2020-07-20 17:13 UTC, kozlovic commented on src/Tests/UnitTests/TestMessageHeaders.cs
> +            Assert.Equal("bar,baz", mh["foo"]);
I don't think this is correct. If there are 2 keys in the headers, you should return an array of strings, not a concatenated, comma separated, string.

2020-07-20 17:13 UTC, kozlovic commented on src/NATS.Client/Msg.cs
> +        new public string this[string name]
I don't think this can be used to represent headers since multiple occurrence of the same key must be stored as an array of values. Also, you should have APIs because if the user tries to Get("foo-key"), you need internally to use the Canonical version: "Foo-Key".
Same when you are going to store the key, you need to store the Canonical version. For deserialization, you should ensure that the keys are canonical.
As previously discussed, the server for instance is not tolerant of a non canonical key. For JetStream and the de-dup feature, the server will look for a header called Msg-Id, and it if it is not stored this way, then that won't work.

2020-07-20 17:59 UTC, ColinSullivan1 commented
@kozlovic , great points - thanks!

Because MsgHeader is a subclass of `NameValueCollection`, one could use the [public virtual string[] GetValues (string name);](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.namevaluecollection.getvalues?view=netcore-3.1) API to return the values as a string array.  The `NameValueCollection` class is a superclass for the .NET HTTP header classes - the string accessor returning comma separated values is an interesting feature that I used as a shortcut in testing.

I'll add tests for the `GetValues` APIs to be sure it works and will make sure multiline keys and values are handled correctly.

2020-07-20 18:01 UTC, ColinSullivan1 commented
I can also add checks to make sure the keys are in canonical form.  The server handled the tests fine though...

2020-07-20 18:17 UTC, kozlovic commented
> I can also add checks to make sure the keys are in canonical form. The server handled the tests fine though...

Because in most cases it does not do anything with the headers. But there is currently 1 case where the server will read headers, it is for JS publish de-dup and in that case it will look for "Msg-Id" and so if the user sets to "msg-id" and library doesn't use canonical form, then server won't de-dup.

2020-07-20 18:26 UTC, ripienaar commented
yeah, server doesnt follow http spec, so gotta be careful. Also soon hopefully we'll add headers for tracing. I dont know .net but since you mentioned a hash I'll also say that order of headers cant change - technically only the order of the same header more than once - but in general its probably a good idea not to tweak order

2020-08-01 00:02 UTC, ColinSullivan1 commented on src/Tests/UnitTests/TestMessageHeaders.cs
> +            Assert.Equal("bar,baz", mh["foo"]);
I've updated the example documentation and tests, look for `string[] values = mh.GetValues("foo");`

2020-08-01 00:04 UTC, ColinSullivan1 commented
FYI, I've made various updates to cover what HTTP headers do, improve performance, and demonstrate multiple values in the documentation example and tests.

2020-08-11 22:29 UTC, ColinSullivan1 commented
Are we g2g?

2020-08-12 13:40 UTC, watfordgnf reviewed
Saw one fix and had some minor comments.

2020-08-12 13:40 UTC, watfordgnf commented on src/NATS.Client/Conn.cs
>              // We only support 4 elements in this protocol version
Is this still 4?

2020-08-12 13:40 UTC, watfordgnf commented on src/NATS.Client/Msg.cs
> +        public char[] stringBuf = new char[64];
This should likely be internal.

2020-08-12 22:16 UTC, ColinSullivan1 commented on src/NATS.Client/Msg.cs
> +        public char[] stringBuf = new char[64];
Oof - thanks - will fix!

2020-08-13 17:55 UTC, watfordgnf approved these changes
Looks good.

2020-08-13 17:59 UTC, ColinSullivan1 commented
Thanks!  Good catch on the size of the args, appreciate it.  Turns out I didn't resize the array - embarrassing, but would have been much more so after a release.  :)

2020-08-13 19:13 UTC, merged