Feature:  Lame Duck Mode Support
nats-io/nats.net.v1 pull request #412
Opened 2020-10-06 20:30 UTC by ColinSullivan1

The NATS Server can enter lame duck mode, whereupon it sends an INFO message with "ldm" enabled to clients.  The NATS client library can notify applications, allowing them to clean up, drain their connection, and gracefully connect to another server.

This PR adds a connection event handler to support this functionality, along with associated tests.  While supported on every platform, tests are only performed on systems that support signaling (not windows).

Resolves #399

Signed-off-by: Colin Sullivan <colin@synadia.com>

2020-10-06 22:54 UTC, matthiashanel requested changes
one condition appears duplicated

2020-10-06 22:54 UTC, matthiashanel commented on src/NATS.Client/Conn.cs
> +            }
if the next block on line 2355 gets skipped because lenght == 0 then line 2368 will be executed.
Together this does the same as this entire block, which makes it redundant. Delete?

2020-10-06 23:35 UTC, ColinSullivan1 commented on src/NATS.Client/Conn.cs
> +            }
It's in case discovered urls are empty.. so if the client is ldm'd and receives empty urls, it's doesn't lose what it has...

2020-10-07 01:49 UTC, matthiashanel commented on src/NATS.Client/Conn.cs
> +            }
but the next check here is ` if (discoveredUrls != null && discoveredUrls.Length > 0)` which is identical.
if discoveredUrls is empty we wouldn't take that if and skip the block.
Then we would execute line 2638 `if (notify && info.ldm && opts.LameDuckModeEventHandler != null)`
This is identical to the code inside this if.
next the function is over, taking the place of return.

2020-10-07 16:28 UTC, matthiashanel approved these changes
LGTM

2020-10-07 16:41 UTC, ColinSullivan1 commented
Thanks for the review @matthiashanel.

2020-10-07 16:42 UTC, merged