WIP - Add No-Responders Feature
nats-io/nats.net.v1 pull request #413
Opened 2020-10-09 22:32 UTC by ColinSullivan1

## Add the No Responders Client Feature

Resolves #400 

When a request is made from the client, if the server detects there is no interest in the request subject (no subscribers), it will immediately return a status header indicating there are no responders.  When this happens, the client will throw a new `NATSNoRespondersException` indicating there are no responders available for a request.  This circuit breaking behavior allows applications to avoid waiting for timeouts for requests that NATS can detect will fail.

The `NATSNoRespondersException` is a subclass of the `NATSTimeoutException` in an effort to maintain some backward compatibility.

Signed-off-by: Colin Sullivan <colin@synadia.com>

2020-10-09 23:40 UTC, matthiashanel reviewed
still working my way through, but got one comment

2020-10-09 23:40 UTC, matthiashanel commented on src/Tests/IntegrationTests/TestBasic.cs
> +                    Assert.True(sw.ElapsedMilliseconds < 5000);
wouldn't you see this as a problem?
Before you'd sit there, thus essentially sleeping.
Now your existing code starts to spin

2020-10-12 16:10 UTC, ColinSullivan1 commented on src/Tests/IntegrationTests/TestBasic.cs
> +                    Assert.True(sw.ElapsedMilliseconds < 5000);
Not sure I understand...  I can see the comment being misleading through.  The request should circuit break by the server's response w/ error code and return much earlier than the 10s configured...  The check is < 5 seconds generous for really, really flaky CI, it's really just checking that it returned earlier than the configured timeout.

2020-10-12 16:14 UTC, ColinSullivan1 commented on src/Tests/IntegrationTests/TestBasic.cs
> +                    Assert.True(sw.ElapsedMilliseconds < 5000);
Ahh - are you saying because NATSNoRespondersException is a subclass of the timeout exception, existing application code could spin if someone had requests in a tight loop...

I wrestled with that a bit.  Throw a new exception (breaking existing code), vs subclassing allowing existing code to succeed but possibly churn.   Tough call.

2020-10-12 16:30 UTC, matthiashanel commented on src/Tests/IntegrationTests/TestBasic.cs
> +                    Assert.True(sw.ElapsedMilliseconds < 5000);
I'd say sending a request in a loop is currently slowed down because on timeout we will have waited.
No need for any extra application logic to do that then.
This does not appear to be opt in... which now would start to cause applications to not wait.

2020-10-12 16:40 UTC, ColinSullivan1 commented on src/Tests/IntegrationTests/TestBasic.cs
> +                    Assert.True(sw.ElapsedMilliseconds < 5000);
Similar problem in go... ;).  However, the difference is nuanced - in go it's a separate error, here it's a subclass.  Are you suggesting clients opt-in?

2020-10-12 16:42 UTC, matthiashanel requested changes
Minor changes

2020-10-12 16:42 UTC, matthiashanel commented on src/NATS.Client/Conn.cs
> +            var subject = args.Message.Subject;
args.Message is also m. use m throughout or delete m

2020-10-12 16:42 UTC, matthiashanel commented on src/NATS.Client/Exceptions.cs
> +    /// /// </summary>
extra ///

2020-10-12 16:42 UTC, matthiashanel commented on src/NATS.Client/Msg.cs
> +                    // check for inlined status:  e.g. "NATS/1.0 503\r\n\r\n"
should we drop the header if 1.0 becomes smth this version of the library does not understand?

2020-10-12 16:43 UTC, matthiashanel commented on src/Tests/IntegrationTests/TestBasic.cs
> +                    Assert.True(sw.ElapsedMilliseconds < 5000);
I'm not saying that the problem does not exist in go either. It's a problem for all code already written.

2020-10-12 17:06 UTC, ColinSullivan1 commented on src/NATS.Client/Conn.cs
> +            var subject = args.Message.Subject;
Will fix...  Thanks.

2020-10-12 17:11 UTC, ColinSullivan1 commented on src/NATS.Client/Msg.cs
> +                    // check for inlined status:  e.g. "NATS/1.0 503\r\n\r\n"
Right now the client will reject the message having an invalid header.

2020-10-12 17:13 UTC, ColinSullivan1 commented on src/NATS.Client/Msg.cs
> +                    // check for inlined status:  e.g. "NATS/1.0 503\r\n\r\n"
I think that behavior is OK because a change in header version would indicate a breaking change - which should need be addressed by updating the client.  wdyt?

2020-10-12 17:17 UTC, matthiashanel reviewed
Code looks good

2020-10-12 17:55 UTC, matthiashanel commented on src/NATS.Client/Msg.cs
> +                    // check for inlined status:  e.g. "NATS/1.0 503\r\n\r\n"
this is not part of this change so probably can be addressed in a separate pr.

Yes it would, but do you really want to risk exposing running clients (not updated yet) to such a header?

2020-10-12 17:59 UTC, matthiashanel commented on src/NATS.Client/Msg.cs
> +                    // check for inlined status:  e.g. "NATS/1.0 503\r\n\r\n"
If we plan for changes once we introduce them we haven't planed for them at all.

2020-10-12 18:01 UTC, matthiashanel approved these changes
LGTM.

header version and disabling this feature can be separate PR

2020-10-12 18:08 UTC, merged