Adjustments to interfaces to improve the mockability and faking of NATS for unit testing in consumer apps.
nats-io/nats.net.v1 pull request #654
Opened 2022-08-05 17:47 UTC by sspates-starbucks

Updated a few interfaces to use IConnection instead of Connection as Connection is internal.  This is preventing mocking libraries from being able to mock properly.
Added interface for ConnectionFactory so factory can be mocked/faked in unit tests.

2022-08-05 18:00 UTC, scottf requested changes
I like this idea but we cannot change the interface in a non backward compatible way.

2022-08-05 18:00 UTC, scottf commented on src/NATS.Client/ISubscription.cs
> +        IConnection Connection { get; }
This would not be backward compatible.

2022-08-05 18:00 UTC, scottf commented on src/NATS.Client/Subscription.cs
> +        public IConnection Connection => conn;
Also not backward compatible.

2022-08-05 22:42 UTC, sspates-starbucks commented
@scottf I removed the IConnection changes, but found that protecting the Message in the handler makes mocking the handling of the message impossible.

2022-08-06 20:06 UTC, scottf commented on src/NATS.Client/IConnectionFactory.cs
> +}
nit: newline at end of file

2022-08-06 20:06 UTC, scottf commented on src/NATS.Client/IConnectionFactory.cs
> +﻿using System;
needs license

2022-08-06 20:09 UTC, scottf commented on src/NATS.Client/Msg.cs
> +            IConnection conn = ArrivalSubscription?.Connection;
Why does this change?

2022-08-06 20:14 UTC, sixlettervariables commented on src/NATS.Client/NATS.cs
> +        public Msg Message { get; set; }
Is there a reason for the setter to be public?

2022-08-06 20:20 UTC, scottf commented
@sspates-starbucks I'm good with the event message changes, not excited about having a public setter, but I suppose it's benign, the worst that could happen is the dev overwrites their own message.
Frankly I'm not seeing the need for the IConnectionFactory interface. There is already an IConnection interface so you can provide your own mock connection if you want to.
And I'll mention again the ability to run a server locally during tests. In .net integration tests we generally start a server for each suite, but for java we start a server for each test.

2022-08-08 22:50 UTC, scottf approved these changes
LGTM

2022-08-08 22:50 UTC, sspates-starbucks commented on src/NATS.Client/NATS.cs
> +        public Msg Message { get; set; }
Fixed

2022-08-08 22:58 UTC, merged