Enable custom TCPConnection implementation
nats-io/nats.net.v1 pull request #767
Opened 2023-05-10 20:06 UTC by tkeller-moxe

This PR expands on the TCPConnection class to be an interface that can be overridden with a options argument to supply a custom interface for implementing the connection class used by the nats client. 

The changes here are modeled after how the Java client handles a custom dialer. 

I included an example of my use case here which is enabling a TLS Reverse proxy to terminate the TLS connection by performing the SSL upgrade before nats communication starts.

2023-05-15 15:31 UTC, tkeller-moxe commented
Rebased, bringing back in line with main.

2023-05-17 15:49 UTC, scottf commented
@tkeller-moxe can you rebase. Should fix the failing tests

2023-05-17 18:47 UTC, scottf commented on src/Samples/TLSReverseProxyExample/TLSReverseProxyExample.csproj
> +  </PropertyGroup>
What is this?

2023-05-17 18:47 UTC, scottf commented on src/NATS.sln
> +# Visual Studio Version 17
Is this necessary to change this file version?

2023-05-17 18:47 UTC, scottf commented on src/NATS.Client/NATS.Client.csproj
> +    <TargetFrameworks>netstandard1.6;netstandard2.0;net46</TargetFrameworks>
Please explain this.

2023-05-17 18:47 UTC, scottf commented on src/Samples/TLSReverseProxyExample/CustomTCPConnection.cs
> +        /// </summary>
Versus waiting for the normal progression of things? Is this why this was done in the first place?

2023-05-17 18:47 UTC, tkeller-moxe commented on src/NATS.sln
> +# Visual Studio Version 17
I can revert this, I just have a newer version of Visual Studio.

2023-05-17 18:48 UTC, tkeller-moxe commented on src/NATS.Client/NATS.Client.csproj
> +    <TargetFrameworks>netstandard1.6;netstandard2.0;net46</TargetFrameworks>
I think this was also VS, I'll remove.

2023-05-17 19:02 UTC, tkeller-moxe commented on src/Samples/TLSReverseProxyExample/CustomTCPConnection.cs
> +        /// </summary>
Yes. My use case is to have a way to start the TLS connection BEFORE the traditional NATS hand shake allowing the connection to go through a load balancer. This PR ultimately tries to mimic the concept of the Custom Dialer used in the Java/Go implementations.

2023-05-17 19:07 UTC, tkeller-moxe commented on src/Samples/TLSReverseProxyExample/TLSReverseProxyExample.csproj
> +  </PropertyGroup>
This example was written in .netcore6, this has it drop the warnings saying that "Package with Version NET 4.6 Maynot be compatible." I can remove this if its a concern as well :)

2023-05-25 15:15 UTC, tkeller-moxe commented
@scottf just following back up! Let me know what other clarity you need.

2023-05-25 15:31 UTC, scottf commented
This is temporarily on hold while our team discusses it. There is already an initiative to change the server behavior and we are considering that this behavior might become the default behavior instead of an add on, but there are consideration such as handling old server versions when the change is made. I know that doesn't help your timeline and I'm not forgetting about it.

2023-05-25 17:03 UTC, tkeller-moxe commented
Understood, Let me know if there is anything I can help with on my end. 

Also an additional comment/musing, I have not tested it nor do I have a strong use case for it. This should actually enable any interface that can mimic the stream class to be used for communication. EG a unix socket is appropriate. Not tested/might want to get some renaming done if that's the remaining use case but I think this is generic enough to cover that as well.

2023-08-04 18:37 UTC, tkeller-moxe commented
I would like to bump this again, It is coming back up in security and networking audits on my end again. 
Thanks!

2023-08-09 14:45 UTC, scottf commented on src/Samples/TLSReverseProxyExample/CustomTCPConnection.cs
> +        /// </summary>
@tkeller-moxe Do you mean custom DataSocket implementation?

2023-08-09 15:06 UTC, tkeller-moxe commented on src/Samples/TLSReverseProxyExample/CustomTCPConnection.cs
> +        /// </summary>
I think that is another proper name for it? 
https://docs.nats.io/using-nats/developer/tutorials/custom_dialer This is what its mimicing.

2023-08-10 08:12 UTC, mtmk commented
Difficult to see the actual change from the diff because of the class extract. For clarity, can we not do the refactor at this stage? (Seems to be causing conflicts as well.)

2023-08-10 08:25 UTC, mtmk requested changes
Please revert TCPConnection class extract refactor for clarity.

2023-08-10 08:25 UTC, mtmk commented on src/NATS.Client/Conn.cs
> -        private sealed class TCPConnection : IDisposable
Can we keep this class here? IMHO it's fine to stay as a nested class if necessary. I just want to make sure I can see all the changes clearly since mistakes here could create massive bugs.

2023-08-10 13:31 UTC, tkeller-moxe commented on src/NATS.Client/Conn.cs
> -        private sealed class TCPConnection : IDisposable
I'll see what I can do, I moved it out for code clarity. 
If I remember I needed to unseal this class and add an interface and IMHO at that point I felt Conn had to many classes and responsibilities. Should be doable I'll try to have this in today :)

2023-08-10 18:20 UTC, mtmk commented
Thanks for the change @tkeller-moxe

Just to note, I see you needed to remove `sealed` from the class so you can extend it. That might introduce overhead (call vs. callvirt, new optimizations etc.) but I doubt it'd be noticeable and probably don't even apply most of the time.

LGTM but would be nice to resolve the conflicts. Are they straight forward to resolve?

2023-08-11 09:32 UTC, mtmk requested changes
Looks good. I have a couple of small requests if that's ok. Should be a quick commit hopefully. Because it's becoming a public interface I thought a little extra care might be good.

2023-08-11 09:32 UTC, mtmk commented on src/NATS.Client/Connection.cs
> +                    throw new NATSException("public error:  Cannot create SslStream from null stream.");
This should stay as 'Internal error'

2023-08-11 09:32 UTC, mtmk commented on src/NATS.Client/Connection.cs
> +            public virtual void open(Srv s, Connection connection, int timeoutMillis)
I suggest to change this signature to:
```
void open(Srv s, Options opts)
```
`Connection` is only used to access options and timeout is part of options already.

2023-08-11 19:32 UTC, mtmk approved these changes
LGTM

2023-08-11 21:35 UTC, merged