Simplified Ordered Consumer
nats-io/nats.net.v1 pull request #802
Opened 2023-07-26 20:53 UTC by scottf

2023-07-27 11:35 UTC, mtmk requested changes

2023-07-27 11:35 UTC, mtmk commented on src/NATS.Client/JetStream/IConsumerContext.cs
> +        /// Create a one use Fetch Consumer using all defaults other than the number of messages. See IFetchConsumer
```suggestion
        /// Create a one use Fetch Consumer using all defaults other than the number of messages. See <see cref="IFetchConsumer"/>
```

2023-07-27 11:35 UTC, mtmk commented on src/NATS.Client/JetStream/IStreamContext.cs
> +        /// <returns></returns>
```suggestion
        /// <returns><see cref="IIterableConsumer"/></returns>
```

2023-07-27 11:35 UTC, mtmk commented on src/NATS.Client/JetStream/IStreamContext.cs
> +        /// <returns></returns>
```suggestion
        /// <returns><see cref="IMessageConsumer"/></returns>
```

2023-07-27 11:35 UTC, mtmk commented on src/NATS.Client/JetStream/MessageConsumerBase.cs
> +        protected ConsumerInfo lastConsumerInfo;
```suggestion
        protected volatile ConsumerInfo lastConsumerInfo;
```
Seen it in `lock`. This would make it thread safe for reads.

2023-07-27 11:35 UTC, mtmk commented on src/NATS.Client/JetStream/MessageConsumerBase.cs
> +                lastConsumerInfo = sub.GetConsumerInformation();
```suggestion
                lock (subLock)
                    if (lastConsumerInfo == null)
                        lastConsumerInfo = sub.GetConsumerInformation();
```
This is the double-check lock. It is a bit confusing. If you prefer just lock both read and write access to `lastConsumerInfo`.

2023-07-27 11:35 UTC, mtmk commented on src/NATS.Client/JetStream/StreamContext.cs
> +        public IMessageConsumer OrderedConsume(OrderedConsumerConfiguration config, EventHandler<MsgHandlerEventArgs> handler,
`OrderedConsume` overloads seems to be returning different things. Would it be confusing for the dev? Feel free to ignore this comment. It might be me.

2023-07-27 12:30 UTC, scottf commented on src/NATS.Client/JetStream/StreamContext.cs
> +        public IMessageConsumer OrderedConsume(OrderedConsumerConfiguration config, EventHandler<MsgHandlerEventArgs> handler,
Not sure what to do here. I'll ask the team

2023-07-27 13:21 UTC, scottf commented on src/NATS.Client/JetStream/IConsumerContext.cs
> +        /// Create a one use Fetch Consumer using all defaults other than the number of messages. See IFetchConsumer
fixed

2023-07-27 13:23 UTC, scottf commented on src/NATS.Client/JetStream/IStreamContext.cs
> +        /// <returns></returns>
fixed

2023-07-27 13:53 UTC, scottf commented on src/NATS.Client/JetStream/IStreamContext.cs
> +        /// <returns></returns>
fixed

2023-07-27 13:53 UTC, scottf commented on src/NATS.Client/JetStream/MessageConsumerBase.cs
> +                lastConsumerInfo = sub.GetConsumerInformation();
discussed

2023-07-27 14:04 UTC, mtmk approved these changes
LGTM

2023-07-28 12:37 UTC, mtmk approved these changes

2023-07-28 16:05 UTC, mtmk approved these changes

2023-07-28 17:05 UTC, mtmk approved these changes

2023-08-01 10:06 UTC, mtmk approved these changes

2023-08-11 21:01 UTC, mtmk reviewed
I think there are a couple of comments might require change. It's mostly suggestions.

2023-08-11 21:01 UTC, mtmk commented on src/NATS.Client/JetStream/ConsumerContext.cs
> +                    throw new ArgumentException($"Max wait must be at least {MinExpiresMills} milliseconds.");
Should we fix it instead of blowing up? i.e. set maxWait to MinExpires quietly, maybe with a warning log

2023-08-11 21:01 UTC, mtmk commented on src/NATS.Client/JetStream/FetchConsumer.cs
> +            pullSubject = ((JetStreamPullSubscription)sub).pullImpl.Pull(pro, false, null);
Is there a chance of invalid cast here? Is there a way to change the type hierarchy to avoid casts?
It's an internal interface so no need to be defensive (i.e. checking types or using `as` or something) so feel free to ignore this comment as long as we're certain that cast will succeed.

2023-08-11 21:01 UTC, mtmk commented on src/NATS.Client/JetStream/FetchConsumer.cs
>          public Msg NextMessage()
Can we make return type nullable and possible document that it may return `null`?

2023-08-11 21:01 UTC, mtmk commented on src/NATS.Client/JetStream/FetchConsumer.cs
> +                    return ((JetStreamPullSubscription)sub)._nextUnmanagedNoWait(pullSubject); // 1 is the shortest time I can give
Public members shouldn't start with underscore, unless I'm missing something here.

2023-08-11 21:01 UTC, mtmk commented on src/NATS.Client/JetStream/IBaseConsumerContext.cs
> +        Msg Next(int maxWaitMillis = BaseConsumeOptions.DefaultExpiresInMillis);
Can we return nullable?

2023-08-11 21:01 UTC, mtmk commented on src/Samples/SimplificationIterableConsumer/IterableConsumerExample.cs
> +                                    report("Post-stop loop running", sw.ElapsedMilliseconds, ++count);
Incrementing count twice. Is that intentional?

2023-08-11 21:01 UTC, mtmk commented on src/Samples/SimplificationMessageConsumer/MessageConsumerExample.cs
> +                    while (!consumer.Finished) {
I know it's just an example but if this is an expected usage pattern `consumer.Finished` must be thread safe.

2023-08-11 21:35 UTC, merged

2023-08-12 01:15 UTC, scottf commented on src/NATS.Client/JetStream/ConsumerContext.cs
> +                    throw new ArgumentException($"Max wait must be at least {MinExpiresMills} milliseconds.");
No. This is a developer coding error. We specifically do not want to provide unexpected behavior.

2023-08-12 01:16 UTC, scottf commented on src/NATS.Client/JetStream/FetchConsumer.cs
> +            pullSubject = ((JetStreamPullSubscription)sub).pullImpl.Pull(pro, false, null);
Unfortunately the hierarchy predates me and was designed this way, I'm working around things as it is. IJetStreamSubscription is the best common base. I agree it's not perfect.

2023-08-12 01:21 UTC, scottf commented on src/NATS.Client/JetStream/FetchConsumer.cs
>          public Msg NextMessage()
Not sure what variable you are talking about or what return.

2023-08-12 01:22 UTC, scottf commented on src/NATS.Client/JetStream/FetchConsumer.cs
>          public Msg NextMessage()
Yes, I will go through and update in a new PR.

2023-08-12 01:23 UTC, scottf commented on src/NATS.Client/JetStream/FetchConsumer.cs
> +                    return ((JetStreamPullSubscription)sub)._nextUnmanagedNoWait(pullSubject); // 1 is the shortest time I can give
That's not a public member, its internal. I could change it to NextUnmanageNoWaitInternal or something. Suggestions?

2023-08-12 01:24 UTC, scottf commented on src/NATS.Client/JetStream/IBaseConsumerContext.cs
> +        Msg Next(int maxWaitMillis = BaseConsumeOptions.DefaultExpiresInMillis);
yes will change in another PR

2023-08-12 01:28 UTC, scottf commented on src/Samples/SimplificationIterableConsumer/IterableConsumerExample.cs
> +                                    report("Post-stop loop running", sw.ElapsedMilliseconds, ++count);
That's a bug, will fix.

2023-08-12 01:34 UTC, scottf commented on src/Samples/SimplificationMessageConsumer/MessageConsumerExample.cs
> +                    while (!consumer.Finished) {
```
public bool Finished { get; internal set; }
```
Not sure what the problem is to just read this variable. It's should not be a problem if it gets changed from false to true in the middle of a read and the user loops one more time.

I could use Interlocked and a backing variable if you think it's critical.

2023-08-12 17:26 UTC, scottf commented on src/NATS.Client/JetStream/IBaseConsumerContext.cs
> +        Msg Next(int maxWaitMillis = BaseConsumeOptions.DefaultExpiresInMillis);
Cannot change. Nullable reference types are not available.
![image](https://github.com/nats-io/nats.net/assets/215946/39409413-f5b8-4cf7-9f0a-9adfbcc6e8b0)

2023-08-12 17:28 UTC, scottf commented on src/NATS.Client/JetStream/FetchConsumer.cs
> +                    return ((JetStreamPullSubscription)sub)._nextUnmanagedNoWait(pullSubject); // 1 is the shortest time I can give
Since it's internal I can change it at any time

2023-08-12 17:29 UTC, scottf commented on src/NATS.Client/JetStream/FetchConsumer.cs
>          public Msg NextMessage()
See comment below

2023-08-14 07:30 UTC, mtmk commented on src/NATS.Client/JetStream/IBaseConsumerContext.cs
> +        Msg Next(int maxWaitMillis = BaseConsumeOptions.DefaultExpiresInMillis);
Sorry, didn't realise the project settings i.e. c# 8.0 support. It's a nice to have. We might be able to introduce it later maybe.

2023-08-14 07:34 UTC, mtmk commented on src/Samples/SimplificationMessageConsumer/MessageConsumerExample.cs
> +                    while (!consumer.Finished) {
A volatile backing field should do it. Assuming setting and getting/checking are done from different threads, the problem is the checking thread might not see the update at all and stay in while loop forever even though the thing is finished.