Subject Validation
nats-io/nats.net.v1 pull request #821
Opened 2023-09-24 19:37 UTC by scottf

2023-09-27 14:11 UTC, mtmk requested changes
looks good in general only one or two minor points need clarification.

2023-09-27 14:11 UTC, mtmk commented on src/NATS.Client/Internals/Validator.cs
> -                        throw new ArgumentException(label + " cannot contain '>'");
I might be missing something but check for '>' being in the middle seems like not being done below.

2023-09-27 14:11 UTC, mtmk commented on src/NATS.Client/Internals/Validator.cs
> +                if (!l2.Contains(t)) {
I don't think this does what it says in the method name [1,2,2] != [1,1,2]

2023-09-27 14:11 UTC, mtmk commented on src/NATS.Client/JetStream/ConsumerConfiguration.cs
> +                    this._filterSubjects = new List<string>();
Can this be called more than once?

2023-09-28 12:12 UTC, scottf commented on src/NATS.Client/Internals/Validator.cs
> -                        throw new ArgumentException(label + " cannot contain '>'");
@mtmk see Line 99

2023-09-28 12:13 UTC, scottf commented on src/NATS.Client/Internals/Validator.cs
> +                if (!l2.Contains(t)) {
I probably need a better name for this and a note. Since it is comparing lists of subject filters, there will never be duplicates

2023-09-28 12:16 UTC, scottf commented on src/NATS.Client/JetStream/ConsumerConfiguration.cs
> +                    this._filterSubjects = new List<string>();
Yes. It's in a builder. This is akin to set/put versus add. I can't change the api name though, I'll just doc it better.

2023-09-28 14:01 UTC, scottf commented on src/NATS.Client/Internals/Validator.cs
> +                if (!l2.Contains(t)) {
```
// This functions tests filter subject equivalency
// It does not care what order and also assume that there are no duplicates.
// From the server: consumer subject filters cannot overlap [10138]
public static <T> boolean consumerFilterSubjectsAreEquivalent(List<T> l1, List<T> l2)
```

2023-09-28 14:06 UTC, scottf commented on src/NATS.Client/JetStream/ConsumerConfiguration.cs
> +                    this._filterSubjects = new List<string>();
Added api doc comment
> Replaces any other filter subjects set in the builder

2023-09-28 21:02 UTC, mtmk commented on src/NATS.Client/Internals/Validator.cs
> -                        throw new ArgumentException(label + " cannot contain '>'");
@scottf ah actually I saw that one. Isn't that checking whether `>` or `*` appearing with in a single token/segment? e.g. `foo.b>ar` I was wondering if you'd need to flag `foo.>.bar` as error as well. (Unless I'm running the function wrongly in my head, in that case please ignore)

2023-09-28 22:49 UTC, scottf commented on src/NATS.Client/Internals/Validator.cs
> -                        throw new ArgumentException(label + " cannot contain '>'");
Got it `foo.*.bar` is okay but not `foo.>.bar`

2023-09-28 23:07 UTC, scottf commented on src/NATS.Client/Internals/Validator.cs
> -                        throw new ArgumentException(label + " cannot contain '>'");
fixed

2023-09-29 03:51 UTC, mtmk approved these changes
LGTM

2023-09-29 12:14 UTC, merged