Direct Message Subject Header May Contain Multiple Subjects
nats-io/nats.net.v1 pull request #830
Opened 2023-10-18 18:23 UTC by scottf

2023-10-18 18:32 UTC, mtmk requested changes
Looks good. Just wanted to check if a bounds check is necessary.

2023-10-18 18:32 UTC, mtmk commented on src/NATS.Client/MsgHeader.cs
> +            return all == null ? null: all[all.Length-1];
Length > 0 would be nice

2023-10-18 18:32 UTC, mtmk commented on src/NATS.Client/MsgHeader.cs
> +            return all == null ? null: all[all.Length-1];
I guess getvalues might return null in that case, so maybe not needed.

2023-10-18 21:03 UTC, scottf commented on src/NATS.Client/MsgHeader.cs
> +            return all == null ? null: all[all.Length-1];
I just did a test to verify. The backing dictionary return null if the key is not present so GetValues returns null as well.

2023-10-19 00:11 UTC, mtmk approved these changes
LGTM

2023-10-19 00:20 UTC, merged