Fix KV allow direct
nats-io/nats.net.v1 pull request #879
Opened 2024-03-14 22:24 UTC by scottf

KV streams require allow_direct set to true. This setting was not done and now is fixed.

2024-03-15 05:49 UTC, mtmk commented on src/Tests/IntegrationTests/TestKeyValue.cs
> +                // TODO COME BACK ONCE SERVER IS FIXED
can we reference what the issue is?

2024-03-15 05:50 UTC, mtmk approved these changes
LGTM - probably good to reference what the issue is in TODO comments

2024-03-18 18:32 UTC, scottf commented on src/Tests/IntegrationTests/TestKeyValue.cs
> +                // TODO COME BACK ONCE SERVER IS FIXED
Yeah, if one is made.

2024-03-18 19:21 UTC, mtmk approved these changes

2024-03-18 19:37 UTC, mtmk requested changes

2024-03-18 19:37 UTC, mtmk commented on src/NATS.Client/JetStream/MessageInfo.cs
> +                try
user `TryParse` instead

2024-03-18 22:15 UTC, scottf commented on src/NATS.Client/JetStream/MessageInfo.cs
> +                try
Multiple values in the header.

2024-03-18 22:19 UTC, mtmk approved these changes
LGTM

2024-03-18 22:20 UTC, merged