pass consumer information in kv store
nats-io/nats.net.v1 pull request #894
Opened 2024-05-20 12:39 UTC by MENNAELMESALMY

2024-05-20 13:49 UTC, scottf requested changes
My initial reaction is that I don't feel good about adding 10 more api. I would be more inclined if you add only 2 more (watch/watch all) with all possible parameters. Also, this has not been approved yet by the client team, I have raised the issue again.

2024-05-20 13:50 UTC, scottf commented on src/NATS.Client/KeyValue/KeyValueConsumerConfiguration.cs
> +    public sealed class KeyValueConsumerConfiguration : JsonSerializable
Does this have to be JsonSerializable? It's not ever written anywhere, it's just a structure.

2024-05-20 13:51 UTC, scottf commented on src/NATS.Client/KeyValue/KeyValueConsumerConfiguration.cs
> +        internal IList<string> GetChanges(KeyValueConsumerConfiguration server)
This isn't necessary. Both GetChanges/RecordWouldBeChange are specific to comparing consumer configuration when it is being used during a jetstream subscribe.

2024-05-20 13:52 UTC, scottf commented on src/NATS.Client/KeyValue/KeyValueWatchSubscription.cs
> +        }
This can't be empty, it has to call the delegate.

2024-05-20 14:16 UTC, MENNAELMESALMY commented on src/NATS.Client/KeyValue/KeyValueConsumerConfiguration.cs
> +    public sealed class KeyValueConsumerConfiguration : JsonSerializable
Yeah, wanted to make it consistent with `ConsumerConfiguration` but that seems unnecessary.

2024-05-20 14:18 UTC, MENNAELMESALMY commented
> My initial reaction is that I don't feel good about adding 10 more api. I would be more inclined if you add only 2 more (watch/watch all) with all possible parameters. Also, this has not been approved yet by the client team, I have raised the issue again.

Updated to include only three, I suppose I can make it only for list of keys as well, what do you think?
Thanks for following up with the team, glad to hear their feedback.

2024-05-20 14:20 UTC, MENNAELMESALMY commented on src/NATS.Client/KeyValue/KeyValueWatchSubscription.cs
> +        }
Sorry can you clarify more on that? 
I think this `this(kv, keyPatterns, watcher, null, fromRevision, watchOptions) ` just calls the other constructor with the configuration as null.

2024-05-20 15:46 UTC, scottf commented on src/NATS.Client/KeyValue/KeyValueWatchSubscription.cs
> +        }
Yeah, sorry, I was in Java land a minute ago...

2024-07-08 17:31 UTC, scottf commented
@MENNAELMESALMY I have an idea for a solution. Since your main objective is to have the ability to know the consumer name, we could add something to `KeyValueOptions` like `WithConsumerNamePrefix`. We would then use the prefix for any consumers the client creates by itself. By adding it to the options we don't have to change or add any api, but would have to make sure all implementation is properly fixed.
As far as meta data, I understand that this solution does not address that.
Other than that, this idea was voted down by the client team, so I'm not sure what else to offer.

2024-08-30 15:54 UTC, closed without merging