test and fix Nkeys.FromPublicKey
nats-io/nats.net.v1 pull request #897
Opened 2024-05-26 17:45 UTC by Zetanova

The currently `Nkeys.FromPublicKey` method produces a `NKeyPair` with an invalid `PublicKey` of 56 bytes

2024-05-27 17:53 UTC, scottf commented
Could you provide code or algorithm to reproduce this?

2024-05-28 05:07 UTC, Zetanova commented
Use the included unit test. The utility function `Nkeys.FromPublicKey` will never produce a valid NKeyPair instance
[src/Tests/UnitTests/TestNkeys.cs](https://github.com/nats-io/nats.net/blob/0d04b28b1a20da56fec4834d77909c9647e0f427/src/Tests/UnitTests/TestNkeys.cs#L84)

2024-05-29 14:24 UTC, scottf commented
@Zetanova This looks good. Could you please add to the main comment a discussion of the primary change, i.e., what was wrong with the old code and why you put in the code that you did.

2024-05-29 14:36 UTC, scottf requested changes

2024-05-29 14:36 UTC, scottf commented on src/NATS.Client/NKeys.cs
> +        #region IDisposable Support
Does this indentation matter?

2024-05-29 14:45 UTC, Zetanova commented on src/NATS.Client/NKeys.cs
> +        #region IDisposable Support
It does not matter. Regions are only for the IDE (collapsible code regions) 
VS2022 did not even show them as changed in the commit
I know it, because I reverted all auto format changes and will try to do it for this one too.

If the project requires a specific format, it needs to be declared with an .editorconfig
reference https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-format

2024-05-29 14:46 UTC, sixlettervariables commented on src/NATS.Client/NKeys.cs
> +        #region IDisposable Support
Whether you indent region directives is a preference thing; bothers my brain to see things akin to a preprocessor directive indented...but it is legal.

2024-05-29 14:51 UTC, Zetanova commented on src/NATS.Client/NKeys.cs
> +        #region IDisposable Support
the proof ...
![image](https://github.com/nats-io/nats.net/assets/1385312/156fe92a-973d-4ce5-b026-2ff9b7e1bb96)

2024-05-29 14:52 UTC, Zetanova commented on src/NATS.Client/NKeys.cs
> +        #region IDisposable Support
I will write to the VS team as a bug, all changes inside a commit should be marked. 

https://developercommunity.visualstudio.com/t/Git-commit-view-window-does-not-show-all/10669950?port=1025&fsid=1a84c04d-2855-4117-a9d3-332895525ca8

2024-05-29 15:10 UTC, scottf requested changes

2024-05-29 15:10 UTC, scottf commented on src/Tests/UnitTests/TestNkeys.cs
> +        }
Can you please change this test to this. I made it this way so I could have a parallel test in Java and to verify that they were both working the same.

```
[Fact]
public void TestNKEYFromPublicKey()
{
    _TestNKEYFromPublicKey("SUAHBVFYZF3DIEO4UIHIZMJICVLURLBM5JJPK7GSVGP2QUC3NZ323BRE6A", "UCM5BG6AAZSEGREBCLG7PG4GFQNJABSAVIXC6VWS7TDHZFPIYFVYHIDG");
    _TestNKEYFromPublicKey("SAADARCQJ3JA737Z443YNAZBNJNTFP7YNAF4QFUXKTBFBS4KAVK55DGSOQ", "AD2HQTUKOPBUGOPHA6KFRE6ZW5TH43D7P7E56OAQBZQLW2ECMNML6MVA");
    _TestNKEYFromPublicKey("SNAH645525YA4PNXHWWS46VNXXQTYAXOPKGHXYAHXZZ43XTDDG2ZQAX7LY", "NBZCD2OSMSDRVYCAI77HUN6A2WNDWNT2DMVVEW66DHNWCDXVOUWRCCK7");
    _TestNKEYFromPublicKey("SOAF5OP7UPK6XJCMNRYEJRET6YQSOE3FD4I4ERSN6WKHLYUC5AQDCOAFVY", "OA6SJACXYP2QGNLU4QYLJTVRVZPCZEEUNO2UQOVNGXYUPUJJHCVZIZQ2");
    _TestNKEYFromPublicKey("SCAP4LGVURDWVL37AZIM5O47UKANFI6FKBY77HMYF55CKW2XFKLNUBTTFE", "CAO36T42KFA2LMIZ6YHJKPQEJWT5ULYSV633FWBCEJ7MREZPHHC56BSC");
}

private static void _TestNKEYFromPublicKey(string userEncodedSeed, string userEncodedPubKey)
{
    NkeyPair userFromSeed = Nkeys.FromSeed(userEncodedSeed);
    NkeyPair userFromKey = Nkeys.FromPublicKey(userFromSeed.EncodedPublicKey);

    Assert.Equal(userFromSeed.PublicKey, userFromKey.PublicKey);
    Assert.Equal(userEncodedPubKey, userFromSeed.EncodedPublicKey);
    Assert.Equal(userEncodedPubKey, userFromKey.EncodedPublicKey);
}
```

2024-05-29 18:10 UTC, Zetanova commented on src/Tests/UnitTests/TestNkeys.cs
> +        }
It's changed now, but with the xunit theory with inline data

2024-05-29 18:20 UTC, scottf approved these changes
LGTM

2024-05-29 18:20 UTC, merged