Add support for clearing old certificates during reconnect
nats-io/nats.net.v1 pull request #919
Opened 2024-09-04 09:07 UTC by TobZip

The `Options` object does not provide a way to remove once added certificates.
This leads to that in case of certificate renewals the connection needs to be closed and recreated, including recreating all subscriptions. Just adding the new certificate and trying to reconnect with the old no longer relevant certificate and the new certificate in the certificate collection will make the connection fail on the TLS handshake.

Without a way to clear the certificates, reflection is required to get access to the internal `certificates` field which can be problematic.

By enabling library user to clear the certificates field through `ClearCertificates()` and adding the new certificate, the connection can use the correct certificate during the next connection retry (if retrial is configured).
This can be done for example in a user provided `ReconnectDelayHandler` method.

Other changes: 
- fixed some typos
- added missing usage of `nameof()`

2024-09-04 10:57 UTC, scottf requested changes
So I'm not going to accept this because it's not necessary. Just make another Options. I do like the other changes, the comment fixes and the nameof for instance, so you are welcome to resubmit with only those changes.

2024-09-04 10:57 UTC, scottf commented on src/NATS.Client/Options.cs
> +        /// Maybe the same as the jwt string if they are chained.</param>
"May be" was correct here. How about, "Both string can contain both the credentials and jwt block since they will be parsed for the required data."

2024-09-04 10:57 UTC, scottf commented on src/NATS.Client/Options.cs
> +	        certificates?.Clear();
Options is "intended" to be immutable. Just make another options object.

2024-09-04 14:19 UTC, TobZip commented on src/NATS.Client/Options.cs
> +	        certificates?.Clear();
Ok, but how do I use this new options object when I have an existing connection? The only way I see is to create a new connection through the connection factory and pass as parameter in `CreateConnection`, or?
I want to avoid recreating the connection object based on the reasons I wrote in the PR description.

2024-09-04 18:27 UTC, scottf commented on src/NATS.Client/Options.cs
> +	        certificates?.Clear();
Ok, I'm convinced, accepting the PR. Thank you for the contribution and the feedback.

2024-09-04 18:27 UTC, scottf approved these changes
LGTM

2024-09-04 18:27 UTC, merged

2024-09-05 03:45 UTC, TobZip commented on src/NATS.Client/Options.cs
> +	        certificates?.Clear();
Great, thanks for your fast answer!

2024-09-05 03:48 UTC, TobZip commented on src/NATS.Client/Options.cs
> +        /// Maybe the same as the jwt string if they are chained.</param>
I did not have time to make this change according to your suggestion before this PR was merged. 
Do you want me to make a new PR to fix this?

2024-09-11 16:15 UTC, scottf commented on src/NATS.Client/Options.cs
> +        /// Maybe the same as the jwt string if they are chained.</param>
sorry for the slow response, yeah, please fix when you get a chance. I'll make a release as soon as you do

2024-11-18 05:47 UTC, TobZip commented on src/NATS.Client/Options.cs
> +        /// Maybe the same as the jwt string if they are chained.</param>
same here, sorry for the even slower response. Will make a new PR this week.

2024-11-18 09:45 UTC, TobZip commented on src/NATS.Client/Options.cs
> +        /// Maybe the same as the jwt string if they are chained.</param>
PR is now created: #925